### ISSUE TITLE
Tests for proceeds take creation time of the RateLimiter into account

### ISSUE THREAD

**Issue by jmfrank63** [antifuchs/governor#143]
I am uncertain if this is intended, I think it is not, but...

My tests were randomly failing with a proceed time of more than 200ms, which I found odd.

Moving the creation of the timestamp after the creation of the limiter gave stable and reasonable results.

However, I am not a really experienced Rust coder, so I might misjudge this. Ignore my PR in this case.

Thank you for this great crate.

**Comment by antifuchs** [comment]
Aaaah, yeah, I think I know what that is: The first time a quanta clock gets created (which probably is on the first test that runs), the clock gets calibrated, which takes a certain number of milliseconds (200 sounds right - it used to be much slower,  [fixed in 0.6.0](https://github.com/metrics-rs/quanta/blob/main/CHANGELOG.md#060---2020-07-06)).

I think putting the "start" timestamp creation after the rate-limiter creation sounds super reasonable, and would fix all those timing issues! I'll take a close look at your PR and get that fix in asap!

**Comment by jmfrank63** [comment]
Please let me know if I should do anything else. I am also working on a
peek method, which is basically the same as check, but does not change the
state of the Rate Limiter. The use case is to limit IP login failures. To
limit them, I have to make a check beforehand I do the authentication if
the next failure resulted in a limit. That is when I call peek. Currently,
the code is not good, it just works ;-). I simply duplicated all relevant
check_one functions and undid the memory state after the decision has been
made.

Is this of interest to you?

Thanks, Johannes

Johannes
Dipl.-Ing. (FH) Johannes-Maria Frank (MSc CS)
30 Craster Square
Newcastle upon Tyne
NE3 3PL
United Kingdom
phone: +447400987848
e-mail: ***@***.***

**Comment by antifuchs** [comment]
I believe this is fixed with #144! Thank you for the contribution (:
